XSD-tricks/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Schema;
using System.Xml.Linq;
using System.IO;
using XSD_tricks.Models;

namespace XSD_tricks.Controllers
{
    public class MainController : Controller
    {
        // GET: Main
        public ActionResult Start()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Start(HttpPostedFileBase file)
        {
            if (file != null && file.ContentType == "text/xml")
            {
                XDocument xdoc = XDocument.Load(file.InputStream);

                Manager mng = new Manager();
                mng.AddNewData(xdoc);
            }
            return View();
        }

        // Демонстрация содержимого БД
        public ActionResult ShowTableData()
        {
            Manager mng = new Manager();
            if (mng.IsEmpty())
                return Content("В таблице нет данных.");
            else
            {
                var records = mng.GetAllConfigRecords(); 
                return PartialView("GetDbData", records);
            }
        }

        // Загрузка данных для полей-параметров сущности ConfigRecord
        public ActionResult ShowParameterData(long pId)
        {
            Manager mng = new Manager();
            var param = mng.GetParamData(pId);

            if (param == null)
                return Content("-");
            return PartialView("GetParamData", param);
        }
    }
}

XSD-tricks/Views/Main/GetDbData.cshtml
@using XSD_tricks.Models;
@model IEnumerable<ConfigRecord>

<table class="table table-bordered">
    <thead>
        <tr>
            <th hidden="hidden">Id</th>
            <th>Connection string</th>
            <th>Query string</th>
            <th>Hotel system</th>
            <th>Id</th>
            <th>Surname</th>
            <th>Name</th>
            <th>Middle name</th>
            <th>Gender</th>
            <th>Birth dath</th>
        </tr>
    </thead>
    <tbody>
        @foreach(ConfigRecord rec in Model)
        {
            <tr>
                <td hidden="hidden">@rec.Id</td>
                <td>@rec.ConnectionString</td>
                <td>@rec.QueryString</td>
                <td>@rec.HotelSystem</td>
                <td>@Html.Action("ShowParameterData", "Main", new { pId = rec.PersonId })</td>
                <td>@Html.Action("ShowParameterData", "Main", new { pId = rec.PersonSurname })</td>
                <td>@Html.Action("ShowParameterData", "Main", new { pId = rec.PersonName })</td>
                <td>@Html.Action("ShowParameterData", "Main", new { pId = rec.PersonMiddleName })</td>
                <td>@Html.Action("ShowParameterData", "Main", new { pId = rec.PersonGender })</td>
                <td>@Html.Action("ShowParameterData", "Main", new { pId = rec.PersonBirthDate })</td>
            </tr>
        }
    </tbody>
</table>

XSD-tricks/Views/Main/GetParamData.cshtml
@model XSD_tricks.Models.ParamRecord

<table class="inner-table table">
    <tr>
        <th>IsNullable</th>
        <td>@Model.IsNullable</td>
    </tr>
    <tr>
        <th>Value</th>
        <td>@Model.Value</td>
    </tr>
    <tr>
        <th>DictionaryName</th>
        <td>@Model.DictionaryName</td>
    </tr>
    <tr>
        <th>Length</th>
        <td>@Model.Length</td>
    </tr>
</table>

@*<p>IsNullable: @Model.IsNullable</p>
<p>Value: @Model.Value</p>
<p>DictionaryName: @Model.DictionaryName</p>
<p>Length: @Model.Length</p>*@

XSD-tricks/Views/Main/Start.cshtml
@{
    ViewBag.Title = "Start";
}

<section class="upload_field">
    <div class="sign"><h2>Загрузка XML-схемы</h2></div>
    @using (Html.BeginForm("Start", "Main", FormMethod.Post, new { enctype = "multipart/form-data" }))
    { 
    <input type="file" name="file" id="btn_getfile" />
    <input type="submit" class="btn btn-default" id="btn_upload" value="Отправить" />
    }
</section>
<div class="splitter"></div>
<section class="db-data_field">
    @Html.Action("ShowTableData")
</section>